# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uc7xCZBcZp7do1kxl-Qdcn3CuOfUfgki
"""

import torch
import yfinance as yf
import pandas as pd
import numpy as np
import librosa
from torch.utils.data import Dataset
from torch.nn.utils.rnn import pad_sequence
from transformers import AutoTokenizer, AutoModelForSequenceClassification

class DataProcessor:
    def __init__(self, device):
        self.device = device
        self.tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")
        self.text_model = AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert").to(self.device)
        self.text_model.eval()

    def get_text_features(self, text):
        inputs = self.tokenizer(text, return_tensors="pt", truncation=True, max_length=512, padding=True).to(self.device)
        with torch.no_grad():
            outputs = self.text_model(**inputs)
        return outputs.logits.cpu().numpy().flatten()

    @staticmethod
    def extract_mfcc_features(raw_audio_array, sampling_rate, n_mfcc=20, max_frames=500):
        try:
            mfccs = librosa.feature.mfcc(y=raw_audio_array, sr=sampling_rate, n_mfcc=n_mfcc).T
            if mfccs.shape[0] > max_frames:
                mfccs = mfccs[:max_frames, :]
            else:
                padding = max_frames - mfccs.shape[0]
                mfccs = np.pad(mfccs, ((0, padding), (0, 0)), mode='constant')
            return torch.tensor(mfccs, dtype=torch.float32)
        except Exception:
            return torch.zeros((max_frames, n_mfcc))

    @staticmethod
    def calculate_forward_volatility(ticker, call_date="2021-04-22", window_days=7):
        try:
            start_date = pd.to_datetime(call_date) - pd.Timedelta(days=5)
            end_date = pd.to_datetime(call_date) + pd.Timedelta(days=window_days + 5)
            stock_data = yf.download(ticker, start=start_date, end=end_date, progress=False)

            if stock_data.empty: return None

            stock_data.index = stock_data.index.tz_localize(None)
            forward_data = stock_data[stock_data.index > pd.to_datetime(call_date)].head(window_days)

            if len(forward_data) < 2: return None

            log_returns = np.log(forward_data['Close'] / forward_data['Close'].shift(1)).dropna()
            return log_returns.std().item()
        except Exception:
            return None


class EarningsMultimodalDataset(Dataset):
    def __init__(self, hf_dataset, ticker_map, processor):
        self.raw_data = hf_dataset
        self.ticker_map = ticker_map
        self.processor = processor
        self.valid_samples = self._process_and_align()

    def _process_and_align(self):
        valid = []
        for i in range(len(self.raw_data)):
            sample = self.raw_data[i]
            company = sample.get('company_name', "")
            ticker = self.ticker_map.get(company, "AAPL") # AAPL acts as fallback for unmatched niche companies

            target = self.processor.calculate_forward_volatility(ticker)
            if target is None: continue

            txt_feats = self.processor.get_text_features(sample['text'][:2000])

            try:
                audio_array = sample['audio']['array']
                sr = sample['audio']['sampling_rate']
            except Exception:
                audio_array, sr = np.random.randn(16000 * 10), 16000

            audio_feats = self.processor.extract_mfcc_features(audio_array, sr)

            valid.append({
                "text_features": torch.tensor(txt_feats, dtype=torch.float32),
                "audio_features": audio_feats,
                "label": torch.tensor([target], dtype=torch.float32)
            })
        return valid

    def __len__(self):
        return len(self.valid_samples)

    def __getitem__(self, idx):
        sample = self.valid_samples[idx]
        return sample["text_features"], sample["audio_features"], sample["label"]


def collate_multimodal(batch):
    txt_list, aud_list, lbl_list = zip(*batch)
    txt_tensor = torch.stack(txt_list)
    lbl_tensor = torch.stack(lbl_list)
    aud_padded = pad_sequence(aud_list, batch_first=True, padding_value=0.0)
    return txt_tensor, aud_padded, lbl_tensor