# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uc7xCZBcZp7do1kxl-Qdcn3CuOfUfgki
"""

import torch
import torch.nn as nn

class MultimodalRiskForecaster(nn.Module):
    """Baseline model: Fuses text and audio using simple vector concatenation."""
    def __init__(self, audio_input_dim=20, lstm_hidden=64, text_dim=3, output_dim=1):
        super(MultimodalRiskForecaster, self).__init__()

        self.audio_lstm = nn.LSTM(
            input_size=audio_input_dim,
            hidden_size=lstm_hidden,
            num_layers=2,
            batch_first=True,
            bidirectional=True
        )

        audio_feature_size = lstm_hidden * 2
        combined_dim = audio_feature_size + text_dim

        self.fc_layers = nn.Sequential(
            nn.Linear(combined_dim, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, output_dim),
            nn.Softplus() # Enforces strictly positive volatility predictions
        )

    def forward(self, text_features, audio_features):
        lstm_out, (hidden, cell) = self.audio_lstm(audio_features)

        forward_hidden = hidden[-2, :, :]
        backward_hidden = hidden[-1, :, :]
        audio_vec = torch.cat((forward_hidden, backward_hidden), dim=1)

        fused_vector = torch.cat((audio_vec, text_features), dim=1)
        prediction = self.fc_layers(fused_vector)
        return prediction


class AttentionRiskForecaster(nn.Module):
    """Proposed model: Fuses text and audio using a Multi-Head Cross-Attention layer."""
    def __init__(self, audio_input_dim=20, lstm_hidden=64, text_dim=3, embed_dim=64):
        super(AttentionRiskForecaster, self).__init__()

        self.audio_lstm = nn.LSTM(
            input_size=audio_input_dim,
            hidden_size=lstm_hidden,
            num_layers=2,
            batch_first=True,
            bidirectional=True
        )

        self.audio_proj = nn.Linear(lstm_hidden * 2, embed_dim)
        self.text_proj = nn.Linear(text_dim, embed_dim)

        self.cross_attention = nn.MultiheadAttention(embed_dim=embed_dim, num_heads=4, batch_first=True)

        self.fc_layers = nn.Sequential(
            nn.Linear(embed_dim, 32),
            nn.ReLU(),
            nn.Linear(32, 1),
            nn.Softplus()
        )

    def forward(self, text_features, audio_features):
        lstm_out, (hidden, cell) = self.audio_lstm(audio_features)
        audio_vec = torch.cat((hidden[-2, :, :], hidden[-1, :, :]), dim=1)

        query = self.audio_proj(audio_vec).unsqueeze(1)
        key_value = self.text_proj(text_features).unsqueeze(1)

        attn_output, attn_weights = self.cross_attention(query, key_value, key_value)

        prediction = self.fc_layers(attn_output.squeeze(1))
        return prediction